print("digite o primeiro numero: ")
primeiro_numero = input ()
print("digite o segundo numero: ")
segundo_numero = input ()
soma = float(primeiro_numero)+ float(segundo_numero)
print(" o valor calculado dos dois números é: ",soma)
